name: Master Build
on:
    push:
        branches: [ master ]
jobs:
    bump:
        if: "!contains(github.event.head_commit.message, '#')"
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Latest Commit
                uses: actions/checkout@v2

            -   name: Bump Version
                id: bump
                uses: Plugily-Projects/version-bump-action@v6
                with:
                    github-token: ${{ secrets.github_token }}
                    git-username: 'Maven-Version-Bot'
                    auto-version-bump: true
            -   name: Print Version
                run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

    publish-pre:
     needs: bump
     runs-on: ubuntu-latest
     steps:
            - name: Checkout Latest Commit
              uses: actions/checkout@v3
              with:
               ref: 'master'
            - name: Set up JDK 17
              uses: actions/setup-java@v1
              with:
               java-version: 17
               
            - name: Build with Maven
              run: mvn -B clean:clean package --file pom.xml
              
            - run: mvn --batch-mode --update-snapshots verify
            
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
               repo_token: "${{ secrets.GITHUB_TOKEN }}"
               automatic_release_tag: "latest"
               prerelease: true
               title: "Development Build"
               files: |
                /target/MinecraftEmergency-*.jar
                README.md
#    test:
#     needs: bump
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up JDK 19
#       uses: actions/setup-java@v3
#       with:
#         java-version: '19'
#         distribution: 'temurin'
#         cache: maven
#     - name: Build with Maven
#       run: mvn -B test --file pom.xml
